"""Add created_at and updated_at columns to claims

Revision ID: 278e331c7032
Revises: 
Create Date: 2025-06-26 22:46:51.855616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '278e331c7032'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('claims', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('claims', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('claims', 'updated_at')
    op.drop_column('claims', 'created_at')
    # ### end Alembic commands ###
